accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    # path('confirm_register_information', views.ConfirmUserInfo.as_view(), name='confirm_user_info'),
    path('login/', views.LogInView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

blog_app/urls.py
from django.urls import path
from . import views


app_name = 'blog_app'

urlpatterns = [
    path('home/', views.HomeView.as_view(), name='home'),
    path('home/post', views.PostView.as_view(), name='post'),
    path('home/post/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/accounts/', include('accounts.urls')),
    path('blog/', include('blog_app.urls')),

]

blog_app/models.py
from django.db import models
from accounts.models import UserManager


# class Blog(models.Model):
#     class Meta:
#         db_table = 'blog'
#
#     user = models.ForeignKey(UserManager, on_delete=models.PROTECT)
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)
#
#     def __str__(self):
#         return str(self.user)


class Post(models.Model):
    class Meta:
        db_table = 'Post'

    user = models.ForeignKey(
        UserManager,
        on_delete=models.PROTECT,
    )
    title = models.CharField(max_length=100)
    image = models.ImageField(
        upload_to='media/',
        blank=True,
    )
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user) + '|' + str(self.title)

blog_app/forms.py
from django import forms
from . models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'image', 'body',)

    def __init__(self, *args, **kwargs):
        self._user = kwargs.pop('user')
        super(PostForm, self).__init__(*args, **kwargs)

    def clean_title(self):
        title = self.cleaned_data['title']
        return title

    def clean_image(self):
        image = self.cleaned_data['image']
        return image

    def clean_body(self):
        body = self.cleaned_data['body']
        return body

    def save(self, commit=True):
        post_info = super(PostForm, self).save(commit=False)
        post_info.user = self._user
        if commit:
            post_info.save()

        return post_info

blog_app/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View, generic
from .models import Post
from accounts.models import UserManager
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login as auth_login
from .forms import PostForm

from django.urls import reverse_lazy


class HomeView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        show_data = Post.objects.filter(user=request.user).order_by('-created_at')
        context = {
            'show_data': show_data,
        }
        return render(request, 'blog_app/home.html', context)


class PostView(LoginRequiredMixin, generic.FormView):
    template_name = 'blog_app/post.html'
    form_class = PostForm
    success_url = reverse_lazy('blog_app:home')

    def get_form_kwargs(self):
        kwargs = super(PostView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    # def get(self,request, *args, **kwargs):
    #     form = PostForm
    #     return render(request, 'blog_app/post.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = PostForm(request.POST, user=request.user)
        if not form.is_valid():
            return render(request, 'blog_app/post.html', {'form': form})

        form.save(commit=True)

        return redirect(reverse('blog_app:home'))


class PostDetailView(LoginRequiredMixin, generic.DetailView):
    queryset = Post.objects.all()

templates/blog_app/home.html
{% extends 'base.html' %}

{% block content %}
<div align="center">
    <h2>Welcome, 「{{ user }}」</h2>
</div>
<body>
    <h3>最新の投稿</h3>
    <table border="3" class="container">
       <tr>
           <th>タイトル</th>
           <th>作成日付</th>
           <th>詳細</th>
       </tr>
    {% for data in show_data.all %}
        <tr>
           <td>{{ data.title }}</td>
            <td>{{ data.created_at }}</td>
            <td><a href="{% url 'blog_app:post_detail' data.pk %}">続きを読む</a></td>
{#			<a href="{% url 'blog_app:post_detail' post.pk %}">続きを読む</a>#}
		</tr>
    {% endfor %}
    </table>
</body>
    <div align="center">
        <a class="btn btn-primary" href="{% url 'blog_app:post' %}">Post</a>
        <a class="btn btn-primary" href="{% url 'accounts:logout' %}">Log out</a>
     </div>
{% endblock %}

templates/blog_app/post.html
{% extends 'base.html' %}

{% block content %}
    <h1>This is Post View.</h1>
    <form action="" method="post">{% csrf_token %}
    <div align="center">
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Post</button>
    </div>
    </form>
{% endblock %}

templates/blog_app/post_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>This is Detail View</h1>
    <div align="center">
<p>タイトル：{{ object.title}}</p>
<p>画像：{{ object.image }}</p>
<p>本文：{{ object.body }}</p>
    <a class="btn btn-primary" href="{% url 'blog_app:home' %}">戻る</a>
    </div>
{% endblock %}